import {expect,test} from '@playwright/test'
import {readFile} from 'node:fs/promises'
import path from 'node:path'

test('overview to dataset profile and LIVE fallback',async({page})=>{await page.goto('/');await expect(page.getByRole('heading',{name:'Turn incomplete catalog rows into defensible product intelligence.'})).toBeVisible();await expect(page.getByText(/LIVE provider unavailable/)).toBeVisible();await page.getByRole('button',{name:'Profile a dataset'}).click();await expect(page.getByText('Know the gaps before enrichment.')).toBeVisible()})

test('upload derives truthful synthetic profile',async({page})=>{await page.goto('/');await page.getByRole('button',{name:/Dataset profile/}).click();await page.getByLabel('Upload catalog CSV').setInputFiles(path.join(import.meta.dirname,'fixtures','catalog.csv'));await expect(page.getByText('Profile ready', {exact:false})).toBeVisible();await expect(page.getByText('2',{exact:true}).first()).toBeVisible();await expect(page.getByText('6',{exact:true})).toBeVisible();await expect(page.getByText('Duplicate part numbers')).toBeVisible()})

test('demo enrichment exposes synthetic evidence and conflict',async({page})=>{await page.goto('/');await page.getByRole('button',{name:/Enrichment review/}).click();const records=page.getByLabel('Demonstration record');await expect(records.locator('option')).toHaveCount(2);await records.selectOption('NOR-DW12Q');await expect(records).toHaveValue('NOR-DW12Q');await page.getByRole('button',{name:'Run DEMO enrichment'}).click();await expect(page.getByText('Synthetic DEMO enrichment persisted.')).toBeVisible();await page.getByRole('button',{name:/ATTRIBUTE_VALUE 3/}).click();await expect(page.getByText(/credible evidence supports different values/i)).toBeVisible();await expect(page.getByText('CREDIBLE_SOURCE_CONFLICT')).toBeVisible();await expect(page.getByText(/demo:\/\/input\/Part_Desc/)).toBeVisible()})

test('correction persists and regenerates descriptions',async({page})=>{await page.goto('/');await page.getByRole('button',{name:/Enrichment review/}).click();await page.getByRole('button',{name:'Run DEMO enrichment'}).click();await expect(page.getByText('Synthetic DEMO enrichment persisted.')).toBeVisible();await page.getByLabel('Correction value').fill('Aster Manufacturing');await page.getByLabel('Reviewer note').fill('Verified during synthetic judge demo');await page.getByRole('button',{name:'Correct'}).click();await expect(page.getByText(/correct saved/)).toBeVisible();await page.getByRole('button',{name:/MOBILE_DESC/}).click();await expect(page.locator('aside').getByText(/Aster Manufacturing Dishwasher/)).toBeVisible();await page.getByRole('button',{name:'Display audit history'}).click();await expect(page.getByRole('heading',{name:'Audit history'})).toBeVisible();await expect(page.getByText(/Verified during synthetic judge demo/)).toBeVisible()})

test('approve and reject actions persist',async({page})=>{await page.goto('/');await page.getByRole('button',{name:/Enrichment review/}).click();await page.getByRole('button',{name:'Run DEMO enrichment'}).click();await expect(page.getByText('Synthetic DEMO enrichment persisted.')).toBeVisible();await page.getByRole('button',{name:'Approve',exact:true}).click();await expect(page.getByText(/approve saved/)).toBeVisible();await page.getByLabel('Rejection reason').fill('Synthetic conflict unresolved');await page.getByRole('button',{name:'Reject',exact:true}).click();await expect(page.getByText(/reject saved/)).toBeVisible();await page.getByRole('button',{name:'Approve product'}).click();await expect(page.getByText('APPROVED',{exact:true})).toBeVisible()})

test('export downloads exact 252-column CSV and audit JSON',async({page})=>{await page.goto('/');await page.getByRole('button',{name:/Enrichment review/}).click();await page.getByRole('button',{name:'Run DEMO enrichment'}).click();await expect(page.getByText('Synthetic DEMO enrichment persisted.')).toBeVisible();const csvDownload=page.waitForEvent('download');await page.getByRole('link',{name:/Export 252-column CSV/}).click();const csv=await csvDownload;const csvText=await readFile(await csv.path() as string,'utf8');expect(csvText.split(/\r?\n/)[0].split(',')).toHaveLength(252);const auditDownload=page.waitForEvent('download');await page.getByRole('link',{name:/Download audit JSON/}).click();const audit=await auditDownload;expect(JSON.parse(await readFile(await audit.path() as string,'utf8')).fields.length).toBeGreaterThan(0)})

test('Quality Centre displays persisted application metrics',async({page})=>{await page.goto('/');await page.getByRole('button',{name:/Quality centre/}).click();await expect(page.getByRole('heading',{name:'Application metrics'})).toBeVisible();await expect(page.getByText('Evidence coverage')).toBeVisible();await expect(page.getByText('Two-example prototype benchmark')).toBeVisible();await expect(page.getByRole('heading',{name:'Automated test inventory'})).toBeVisible()})
