import {AlertCircle,Check,Download,FileJson,Loader2,RefreshCw,X} from 'lucide-react'
import {useEffect,useState} from 'react'
import {Confidence} from '../components/Confidence'
import type {Field,PersistedProduct} from '../types'

type DemoRow={Mfg_Part_Num:string;Part_Desc:string;E1_Brand:string;Unilog_Brand:string;DIB_Brand:string;Part_Manuf:string}

export function Review(){
 const [fixtures,setFixtures]=useState<DemoRow[]>([]),[fixture,setFixture]=useState<DemoRow|null>(null),[product,setProduct]=useState<PersistedProduct|null>(null),[selected,setSelected]=useState<Field|null>(null)
 const [loading,setLoading]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[correction,setCorrection]=useState(''),[note,setNote]=useState(''),[reason,setReason]=useState(''),[audit,setAudit]=useState<Record<string,unknown>|null>(null)
 useEffect(()=>{fetch('/api/v1/demo/products').then(r=>r.json()).then((rows:DemoRow[])=>{setFixtures(rows);setFixture(rows[0])}).catch(()=>setError('Demo fixtures are unavailable.'))},[])
 async function run(){if(!fixture)return;setLoading(true);setError('');try{const response=await fetch('/api/v1/enrich/demo/persist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(fixture)});const body=await response.json();if(!response.ok)throw new Error(body.error?.message||'Enrichment failed');setProduct(body);setSelected(body.fields[0]);setSuccess('Synthetic DEMO enrichment persisted.')}catch(e){setError(e instanceof Error?e.message:'Enrichment failed')}finally{setLoading(false)}}
 async function fieldAction(action:'APPROVE'|'CORRECT'|'REJECT'){if(!selected?.id)return;setError('');if(action==='CORRECT'&&(!correction.trim()||!note.trim())){setError('Correction value and reviewer note are required.');return}if(action==='REJECT'&&!reason.trim()){setError('A rejection reason is required.');return}try{const response=await fetch(`/api/v1/fields/${selected.id}/review`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,value:action==='CORRECT'?correction:undefined,note:note||undefined,reason:reason||undefined,reviewer:'prototype-reviewer'})});const body=await response.json();if(!response.ok)throw new Error(body.error?.message||'Review action failed');setProduct(body);setSelected(body.fields.find((field:Field)=>field.id===selected.id)||body.fields[0]);await fetch('/api/v1/quality');setSuccess(`${action.toLowerCase()} saved. Descriptions and quality metrics refreshed.`);setCorrection('');setNote('');setReason('')}catch(e){setError(e instanceof Error?e.message:'Review action failed')}}
 async function productAction(action:'APPROVE'|'REJECT'){if(!product)return;const response=await fetch(`/api/v1/products/${product.id}/review`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,reviewer:'prototype-reviewer',reason:action==='REJECT'?'Judge demo rejection':undefined})});const body=await response.json();if(response.ok){setProduct(body);setSuccess(`Product ${action.toLowerCase()} saved.`)}else setError(body.error?.message||'Product action failed')}
 async function loadAudit(){if(!product)return;const response=await fetch(`/api/v1/products/${product.id}/audit.json`);if(response.ok)setAudit(await response.json());else setError('Audit report unavailable.')}
 return <div className="fade max-w-7xl"><div className="eyebrow">Synthetic evidence review</div><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-4xl font-extrabold tracking-tight">Every value earns its place.</h1><p className="mt-2 text-sm text-steel">Confidence is an explainable score from evidence trust, directness, agreement and validation. Human review resolves uncertainty.</p></div>{product&&<span className="mono border border-ink px-3 py-2 text-xs font-bold">{product.review_status}</span>}</div>
 <section className="panel mt-7 p-5"><label className="eyebrow" htmlFor="demo-record">Demonstration record</label><div className="mt-3 flex flex-col gap-3 md:flex-row"><select id="demo-record" className="flex-1 border border-line bg-white px-4 py-3" value={fixture?.Mfg_Part_Num||''} onChange={e=>setFixture(fixtures.find(row=>row.Mfg_Part_Num===e.target.value)||null)}>{fixtures.map(row=><option key={row.Mfg_Part_Num} value={row.Mfg_Part_Num}>{row.Mfg_Part_Num} · {row.Part_Desc}</option>)}</select><button onClick={run} disabled={!fixture||loading} className="bg-ink px-6 py-3 font-bold text-white disabled:opacity-50">{loading?'Enriching…':'Run DEMO enrichment'}</button></div><p className="mt-3 text-xs text-steel">All records, evidence and `demo://` identifiers on this screen are synthetic and public-safe.</p></section>
 {error&&<div role="alert" className="mt-4 flex gap-2 border border-red-700 bg-red-50 p-4 text-sm text-red-800"><AlertCircle size={18}/>{error}</div>}{success&&<div role="status" className="mt-4 flex gap-2 border border-emerald-700 bg-emerald-50 p-4 text-sm text-emerald-800"><Check size={18}/>{success}</div>}{loading&&<div className="mt-5 flex gap-2"><Loader2 className="animate-spin"/> Building synthetic evidence ledger…</div>}
 {product&&<><div className="mt-6 flex flex-wrap gap-2"><button onClick={()=>productAction('APPROVE')} className="bg-ink px-4 py-2 text-sm font-bold text-white">Approve product</button><button onClick={()=>productAction('REJECT')} className="border border-red-700 px-4 py-2 text-sm font-bold text-red-700">Reject product</button><a download href={`/api/v1/products/${product.id}/export.csv`} className="flex items-center gap-2 border border-ink px-4 py-2 text-sm font-bold"><Download size={15}/> Export 252-column CSV</a><a download href={`/api/v1/products/${product.id}/audit.json`} className="flex items-center gap-2 border border-ink px-4 py-2 text-sm font-bold"><FileJson size={15}/> Download audit JSON</a><button onClick={loadAudit} className="flex items-center gap-2 border border-line px-4 py-2 text-sm"><RefreshCw size={15}/> Display audit history</button></div>
 <div className="mt-5 grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><div className="panel max-h-[620px] overflow-auto"><div className="sticky top-0 grid grid-cols-[1fr_1fr_110px] bg-ink px-5 py-3 text-xs font-bold uppercase text-white"><span>Field</span><span>Value</span><span>State</span></div>{product.fields.map(field=><button key={field.id} onClick={()=>setSelected(field)} className={`grid w-full grid-cols-[1fr_1fr_110px] border-b border-line px-5 py-4 text-left focus-visible:outline focus-visible:outline-2 ${selected?.id===field.id?'bg-signal/20':'hover:bg-white'}`}><span className="mono text-xs font-bold">{field.field_name}</span><span className="truncate pr-3 text-sm">{field.generated_value??'Withheld'}</span><span className={`text-[10px] font-bold ${field.review_status==='CONFLICT'?'text-red-700':field.review_status==='NEEDS_REVIEW'?'text-amber-700':'text-emerald-700'}`}>{field.review_status}</span></button>)}</div>
 {selected&&<aside className="panel h-fit p-6"><div className="eyebrow">Evidence ledger · synthetic</div><h2 className="mt-2 text-lg font-extrabold">{selected.field_name}</h2>{selected.review_status==='CONFLICT'&&<div role="alert" className="mt-4 bg-red-50 p-3 text-sm text-red-800">Conflict means credible evidence supports different values; CatalogIQ preserves every candidate.</div>}<div className="mt-5 text-xl font-bold">{selected.generated_value??'No value proposed'}</div><div className="mt-5"><Confidence value={selected.confidence}/></div><div className="mt-4 flex flex-wrap gap-1">{selected.reason_codes?.map(code=><span className="mono bg-amber-50 px-2 py-1 text-[10px]" key={code}>{code}</span>)}</div>{selected.candidates?.map((candidate,i)=><div className="mt-2 border border-line p-3 text-sm" key={i}><strong>{candidate.value}</strong><div className="text-xs text-steel">{candidate.source} · {Math.round(candidate.confidence*100)}%</div></div>)}{selected.evidence.map((e,i)=><div className="mt-3 bg-paper p-3 text-sm" key={i}><p>“{e.excerpt}”</p><div className="mono mt-2 text-[10px] text-steel">{e.source_identifier} · synthetic</div></div>)}<div className="mt-5 space-y-2"><label className="eyebrow" htmlFor="correction">Correction value</label><input id="correction" value={correction} onChange={e=>setCorrection(e.target.value)} className="w-full border border-line p-2"/><label className="eyebrow" htmlFor="review-note">Reviewer note</label><input id="review-note" value={note} onChange={e=>setNote(e.target.value)} className="w-full border border-line p-2"/><label className="eyebrow" htmlFor="reject-reason">Rejection reason</label><input id="reject-reason" value={reason} onChange={e=>setReason(e.target.value)} className="w-full border border-line p-2"/></div><div className="mt-4 grid grid-cols-3 gap-2"><button onClick={()=>fieldAction('APPROVE')} className="bg-ink p-2 text-xs font-bold text-white">Approve</button><button onClick={()=>fieldAction('CORRECT')} className="border border-ink p-2 text-xs font-bold">Correct</button><button onClick={()=>fieldAction('REJECT')} className="border border-red-700 p-2 text-xs font-bold text-red-700">Reject</button></div></aside>}</div>
 {audit&&<section className="panel mt-5 p-5"><div className="flex justify-between"><h2 className="font-bold">Audit history</h2><button aria-label="Close audit history" onClick={()=>setAudit(null)}><X size={17}/></button></div><pre className="mt-3 max-h-72 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(audit,null,2)}</pre></section>}</>}
 {!product&&!loading&&<div className="panel mt-6 p-8 text-center text-steel">Choose a synthetic record and run enrichment to begin the persisted review journey.</div>}</div>
}
