import {cleanup,render,screen} from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import {afterEach,describe,expect,it,vi} from 'vitest'
import App from './App'

afterEach(()=>{cleanup();vi.restoreAllMocks()})
const fixture={Mfg_Part_Num:'AST-DW14X',Part_Desc:'Synthetic dishwasher 120 V',E1_Brand:'Aster',Unilog_Brand:'-',DIB_Brand:'-',Part_Manuf:'Aster Works'}
const product={id:7,manufacturer_part_number:'AST-DW14X',review_status:'NEEDS_REVIEW',fields:[{id:11,field_name:'MANUFACTURER_NAME',original_value:'Aster Works',generated_value:'Aster Works',evidence:[{excerpt:'Synthetic dishwasher 120 V',source_identifier:'demo://input/Part_Desc',extraction_method:'synthetic-deterministic-parser'}],confidence:.76,validation_status:'VALID',review_status:'NEEDS_REVIEW',reason_codes:[],candidates:[]}]}
function response(body:unknown,ok=true){return Promise.resolve({ok,json:async()=>body})}

describe('CatalogIQ judge workflow',()=>{
 it('shows provider fallback and state-derived quality',async()=>{vi.stubGlobal('fetch',vi.fn((input:string|URL|Request)=>String(input).includes('/quality')?response({field_count:0,input_row_count:1000,placeholder_count:2595,duplicate_count:0,processing_duration_ms:20,evidence_coverage:null,schema_valid_percentage:null,validated_field_percentage:null,conflict_count:0,human_review_count:0,source_policy_rejection_count:0,automated_test_inventory:['backend']}):response({providers:{gemini:false}})));render(<App/>);expect(await screen.findByText(/LIVE provider unavailable/)).toBeInTheDocument();expect(screen.getAllByText('DEMO MODE · LOCAL · SECURE').length).toBeGreaterThan(0);await userEvent.click(screen.getByRole('button',{name:/Quality centre/}));expect(await screen.findByText('1000')).toBeInTheDocument()})
 it('persists a correction with reviewer note',async()=>{const fetchMock=vi.fn((input:string|URL|Request)=>{const url=String(input);if(url.includes('/demo/products'))return response([fixture]);if(url.includes('/persist'))return response(product);if(url.includes('/review'))return response({...product,fields:[{...product.fields[0],generated_value:'Aster Manufacturing',review_status:'APPROVED'}]});if(url.includes('/quality'))return response({});return response({providers:{gemini:false}})});vi.stubGlobal('fetch',fetchMock);render(<App/>);await userEvent.click(screen.getByRole('button',{name:/Enrichment review/}));await userEvent.click(await screen.findByRole('button',{name:'Run DEMO enrichment'}));expect(await screen.findByText('Synthetic DEMO enrichment persisted.')).toBeInTheDocument();await userEvent.type(screen.getByLabelText('Correction value'),'Aster Manufacturing');await userEvent.type(screen.getByLabelText('Reviewer note'),'Verified synthetic evidence');await userEvent.click(screen.getByRole('button',{name:'Correct'}));expect(await screen.findByText(/correct saved/)).toBeInTheDocument();expect(fetchMock).toHaveBeenCalledWith('/api/v1/fields/11/review',expect.objectContaining({method:'POST'}))})
 it('shows source-policy rejection',async()=>{vi.stubGlobal('fetch',vi.fn((input:string|URL|Request)=>String(input).includes('/sources/retrieve')?response({ok:false,url:'https://amazon.com/x',text:'',content_type:null,error_code:'MARKETPLACE_PROHIBITED',policy:{source_type:'PROHIBITED_MARKETPLACE',reason_code:'MARKETPLACE_PROHIBITED',trust_weight:0}}):response({providers:{gemini:false}})));render(<App/>);await userEvent.click(screen.getByRole('button',{name:/Source retrieval/}));await userEvent.type(screen.getByLabelText('Source URL'),'https://amazon.com/x');await userEvent.click(screen.getByRole('button',{name:'Retrieve'}));expect(await screen.findByText('Source unavailable')).toBeInTheDocument()})
})
